### ISSUE TITLE
Simplify redundant `N` and `dims`

### ISSUE THREAD

**Issue by prisae** [PyLops/pylops#123]
Some calls take an `N` and a `dims` parameter, e.g., `pylops.FirstDerivative`. The `N` is redundant, as it can be derived from `dims`.

This is there for legacy reasons and should be cleaned-up for v2.0.0 (@mrava87 you can tag that for the milestone/project board).

Also, as it happens in the same instance call, replacing the `dir` with `axis` (like used in NumPy/SciPy).

**Comment by mrava87** [comment]
@cako this is done right, ready to be closed?

**Comment by prisae** [comment]
Oh wow, Dec 2019, I definitely do not remember having opened this issue :-)

**Comment by cako** [comment]
Yes, this is closed by #310 and #332!
