### ISSUE TITLE
Dot product test checkimag same as checkreal

### ISSUE THREAD

**Issue by ar4** [PyLops/pylops#229]
`checkimag` seems to be the same as `checkreal`, but I suspect that the `np.real`s should be changed to `np.imag`s:
https://github.com/PyLops/pylops/blob/9c7ad688c3333ba68bb2ccbbf3e6f3a6999e5e66/pylops/utils/dottest.py#L104

**Comment by mrava87** [comment]
Hi @ar4, 
good catch!

I quickly checked rerunning all our tests after fixing this locally and only one dottest failed in `test_Bilinear_2dsignal`). I needed to change the dtypes in the dictionaries at the top of the `test_interpolation.py` from float32->float64 and complex64->complex128. Other than that all other tests pass (meaning we never checked the imag component but things were still done correctly, phew! ;) )

Happy to make a PR or shall I do?

**Comment by ar4** [comment]
Hi @mrava87,

That's good news that the test didn't reveal any problems. It sounds like you have all of the work done already, so it's probably fastest for you to submit the fix.

**Comment by mrava87** [comment]
Sounds good, I am doing it and you can have a look if you agree with the change :)

**Comment by mrava87** [comment]
We should think about changing print statements to f-string so we don't need to handle real-complex prints differently. See discussion in https://github.com/PyLops/pylops/pull/231

**Comment by mrava87** [comment]
Added dedicated issue for f-string https://github.com/PyLops/pylops/issues/283
