### ISSUE TITLE
Suggested improvement for api/generated/pylops.optimization.sparsity.OMP

### ISSUE THREAD

**Issue by AdriaJ** [PyLops/pylops#244]
Please describe what could be improved about this page or the typo/mistake that you found:

There is an inconsistency in the definition of the $\sigma$ parameter. In the documentation, it is described as the L2 norm of the residual, whereas in the following notes it is compared to the squarred norm of the residual.

The implementation is consistent with the documentation. To avoid further misunderstanding (I might not be the only one mistaken by the notes), I suggest to add an exponent 2 to the $\sigma$ in the notes.

**Comment by mrava87** [comment]
Thanks, you are correct. We have fixed it https://github.com/PyLops/pylops/pull/245 :)
