### ISSUE TITLE
f-strings

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#283]
f-strings are becoming the standard way to write print/warning messages in Python. 

Most of our current codebase uses old format and should be revisited if we want to start introducing f-strings as we progress.

**Comment by cako** [comment]
Just a comment regarding this issue. Logging should generally use printf-style strings:

https://docs.python.org/3/howto/logging.html#optimization

https://blog.pilosus.org/posts/2020/01/24/python-f-strings-in-logging/
