### ISSUE TITLE
Warn user when using a type other than float64 or complex128 in FFT

### ISSUE THREAD

**Issue by cako** [PyLops/pylops#286]
_As a user, I would like to ensure that when I use a LinearOperator with `float128` or `complex256` dtype, I maintain the precision. Similarly, when using a LinearOperator with `float 32` or `complex64` (or even lower, like `float16`), I would like to make sure I am not doing extraneous computations with higher precision types._

This behavior does not happen with `FFT` when relying on the NumPy ([see this issue](https://github.com/numpy/numpy/issues/17801)) or pyfftw backends, which automatically casts results to `complex128`. Therefore, it makes sense to warn the user that the computations will be done in `complex128` and will then be cast to the operator `dtype`. Note that both `scipy.fft` and the legacy `scipy.fftpack` return the correct types, so we should consider implementing these in separate PR.

## Definition of done
1. Warn user when a provided dtype is not `float64` or `complex128`.

**Comment by mrava87** [comment]
+1 for scipy option :)

**Comment by mrava87** [comment]
And I agree with the suggestion, so far we do the cast for the user but do not fully explain why. Maybe worth adding it to the notes
