### ISSUE TITLE
Describe method

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#293]
Design a utility routine called `describe` that takes as input a PyLops operator and creates the equivalent mathematical expression to be printed on screen. Leverage ``simply`` to simplify the task of  creating mathematical expressions.

## Definition of done

- Be able to pass any operator to the describe method and obtain the equivalent mathematical expression on screen (in LaTex format when running the command from a Jupyter Notebook)
- Add ``name`` property to all PyLops operators and initialize to the name of the operator. In order to avoid doing so for each operator individually, we should start calling the super-method when initializing any of PyLops operators and add name as one of the optional properties of the main class.

**Comment by mrava87** [comment]
The first goal is achieved. We keep the Issue open until the second one is also addressed (so far users can 'aggressively' add a name property to their operators).

**Comment by mrava87** [comment]
@cako when you have time, do you mind taking a look at this PR and let me know if you have any comment or suggestion. This notebook https://github.com/PyLops/pylops_notebooks/blob/master/developement/Sympy.ipynb may also help :)

**Comment by cako** [comment]
Hi @mrava87, I had a look at the commits and it looks very good to me. I can't say I understand the code fully, but just trying out some examples everything worked out. With that said, I have a few suggestions on how to improve before we add to master.

1. I agree that the name should be part of the main `LinearOperator` class. I'm not sure what the best approach is in terms of design, but I will investigate this a bit further.
2. I'm not too comfortable with the random assigning of operator names. It became really confusing after a while when using a few operators without the `name` attribute. I think a nicer solution to this problem would be to assign a base name descriptive of the operator ("FFT", "Shift", etc.) upon creation, and adding numbers whenever you identify duplicates. This will be clearer in the sense that you will know what the "nameless" operators are doing and which ones correspond to your equations (from the numbering).

I'll keep playing around but for now those are my 2 cents!

**Comment by mrava87** [comment]
Hi @cako 
thanks!

1. I am playing a bit with it. My initial idea was to simply extend the `LinearOperator` like this:
```
    def __init__(self, Op=None, explicit=False, clinear=None, name=None):
        self.explicit = explicit
        if Op is not None:
            self.Op = Op
            self.shape = self.Op.shape
            self.dtype = self.Op.dtype
            self.clinear = getattr(self.Op, "clinear", True)
        if clinear is not None:
            self.clinear = clinear
        self.name = name

```
and start calling the `super` method in all operators (eg for Diagonal):

```
def __init__(self, diag, dims=None, dir=0, dtype="float64", name=None):
...
super().__init__(explicit=False,
                         clinear=True,
                         name=name)
```

2. This is a good idea, I think it is doable and maybe less confusing as you say than having random names. I did a quick test and I think makes sense. So the idea would be to define the default name not as `None` like my initial code above did but with the name of the operator (possibly all in small letters apart from the first otherwise it gets a bit confusing). We `reserve` capital letters for start of name or compact name (at least as suggestion to users)

<img width="599" alt="Screen Shot 2022-01-17 at 9 30 03 AM" src="https://user-images.githubusercontent.com/22675848/149718902-d70aef20-abb6-4838-bc48-26b8f0f458fb.png">

What do you think?

**Comment by mrava87** [comment]
@cako I am still not convinced what is better, opinion?

Just random characters:
<img width="953" alt="Screenshot 2022-03-20 at 9 40 34 PM" src="https://user-images.githubusercontent.com/22675848/159177498-de651b18-7de8-445a-bc62-c1f111a46986.png">
Verbose names:
<img width="924" alt="Screenshot 2022-03-20 at 9 40 43 PM" src="https://user-images.githubusercontent.com/22675848/159177513-aa3b79b4-1234-4650-bb69-dc8b1678ae99.png">

As an idea the second one sounds better but when I look at it I find it a bit distracting... think especially if all of the operators are so long. Even more so when you have two operators or the same kind (eg laplacian), then this will read `Secondderivative+Secondderivative1`...

I have pretty much implemented the entire basicoperators submodule adding `name` as optional input, I just need to decide if I fix it to `None` allowing the random character generator or to a verbose name. Let's agree before I push :)

**Comment by mrava87** [comment]
Alright, good we agree on the long verbose names. Let me give it a try with short letters augmented by numbers (suffixes if simply allows it). I'll make PR with only the basicoperators once I am there, once you agree I can go ahead and do the same for all the other submodules :)

**Comment by mrava87** [comment]
Right, I decided to go for a middle way: every operator has a default name equal to its initial (eg Diagonal=D). Now if multiple operators with the same initial appear the first stays as is, the others change name. 

I wanted to just add a suffix but the bookkeeping was becoming a bit too messy, for now the only bookkeeping I do is the number of operators and if this is larger than 26 (letter of alphabets) I start to promote _1 suffix. Have a look at this notebook and let me know what you think https://github.com/PyLops/pylops_notebooks/blob/master/developement/Describe.ipynb

I will then do the same for all other submodule and have one unique PR :)

**Comment by mrava87** [comment]
Btw, when you take a look at the notebook I will be interested to know if you understand why a for loop makes operators with different ids but a list comprehension doesn't

**Comment by cako** [comment]
Sorry it took me so long to get to this. I like your solution, I played around with it and it works quite nicely. For now let's go ahead and keep this solution. With regards to your question about the different ids, I think the issue is that you are not using a list comprehension, but actually a list repetition.

Your code:
```python
# Same ids
M = [pylops.MatrixMult(np.random.normal(0,1,(5,5)))] * 4
```
List comprehension
```python
# Different ids
M = [pylops.MatrixMult(np.random.normal(0, 1, (5, 5))) for _ in range(4)]
```

**Comment by cako** [comment]
Before we move on entirely from this issue, I just wanted to share some thoughts about naming collisions. The way TensorFlow handles this is by keeping track *globally* of all names called. This is done [in this function](https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/backend.py#L1137). I think, for the future, we could try implementing something of the sort. Another interesting behavior in TF is that two layers within the same model cannot have the same name trying to do this will result in a `ValueError`. However, defining them outside a model has no problems. Again, maybe, we can think of a way to incorporate similar behavior in PyLops? I'm not sure what is the best approach, though.

**Comment by mrava87** [comment]
Thanks! Sorry my bad on the list repetition, I didn't think about the implications of `* 4`. 

Good idea to look at TF as they must keep track of names and use them when the crawl through the graph. Let me take a look and see if we can readapt our `_assign_name` a bit following some of what they do :)

**Comment by mrava87** [comment]
I am also not yet happy with Laplacian as after some of the latest changes 

```
A = pylops.Laplacian((5,3))

# Simple operator
describe(A)
```

gives `2S`, whilst it should be something like `S+B`. I put here so I don't forget before closing this issue. I think we need to be more careful how we carry the names across (this doesn't seem to work well with `_SumLinearOperator` and `_ProdLinearOperator` yet :(

**Comment by cako** [comment]
So I don't forget, there is a bug in describe: https://www.youtube.com/watch?v=RIeVkuY_ivQ&t=5355s

**Comment by mrava87** [comment]
@cako can you please try running this again. 
I think the fact you added _SumLinearOperator directly in LinearOperator led to this behavior.. and this https://github.com/PyLops/pylops/commit/66ae8acf471e4eee4f64e3b3ffad82dbccae2f4b should have fixed it

**Comment by cako** [comment]
Yup, it's fixed!
