### ISSUE TITLE
Add warning to FFT2D

### ISSUE THREAD

**Issue by cebirnie92** [PyLops/pylops#295]
When initialising FFT2D it would be nice to have a warning or error thrown if using an nt that is bigger than nfft. 

For example, the following code should throw a warning: 

```
    nt = d.shape[0]  # 2**12
    nfft_k = nfft_f = 2**10
    F = FFT2D(dims=(nt, nr), nffts=(nfft_f, nfft_k), sampling=[dt, dx], dtype=np.float)

**Comment by mrava87** [comment]
Thanks!

@cako : Claire was using FFT2D and accidentally chose nfft<nt and got this error:

```
y = np.take(y, range(self.dims[self.dirs[1]]), axis=self.dirs[1])
...
IndexError: index 128 is out of bounds for axis 1 with size 128
```

I kind of do this all the time and soon realize the mistake but I can see that for a normal user the error thrown right now may be not obvious. I wanted to check what you think:

- 1. shall we immediately raise an error during initizialization if any of the nfft is smaller than the corresponding dimension in the original domain?
- 2. can you think of any case where someone may want an fft shorter than the original domain? By doing so you lose info as under the hood classic FFT implementations truncate the input and then apply FFT, so I would be tempted to say no... if this is the case then we should not bother accommodating for this and revert to raising an error, but if this is the case it may be better to change the way we truncate (checking if nfft is bigger and do it only when this is the case (and possibly pad in the other scenario).

I can easily fix all FFTs in either way, but just wanted a second opinion before I move on :)

**Comment by cako** [comment]
I personally cannot see a reason for anyone to use a smaller nfft than nt. I'm also not too worried about accommodating this case as it can easily be achieved by cropping the input vector as you mentioned. At the same time I'm not a fan of the idea of simply banning the user from doing so: I think we need to keep in line with the philosophy that our users know what they are doing.

Maybe a good middle ground is to allow nfft < nt but warn that input signals will be cropped in accordance to NumPy/SciPy behavior.

**Comment by mrava87** [comment]
Sounds like a good deal!

So, we basically keep all as it is but we add a warning to tell users that what they are doing (nfft<nt) will risk losing some of the signal as FFT truncates upfront... and we can simply check nfft vs the dims and when this is smaller replace np.take with np.pad... that should work :)

I'll give it a go and see
