### ISSUE TITLE
Atol and Btol in scipy lsqr

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#327]
## Problem
From version `1.8.0` scipy's `atol` and `btol` for `scipy.sparse.linalg.lsqr` have been changed from 1e-8 to 1e-6. Since we usually do not specify them in our test suite when using lsqr, some of our tests started failing (see https://github.com/PyLops/pylops/issues/325).

## Completed
For the moment atol and btol have been fixed to the previous value (1e-8) in all tests that are failing. We however want this to propagate to all tests to avoid problems in future

**Comment by dikwickley** [comment]
@mrava87 is this issue still still open?

**Comment by mrava87** [comment]
Yea, this is still relevant

**Comment by dikwickley** [comment]
I would be working on this.
