### ISSUE TITLE
Depracation routines

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#339]
In the process of moving to v2.x we should consider the suggestion in https://github.com/PyLops/pylops/pull/336#issuecomment-1046220631 aimed at creating methods that can help users understand what has been deprecated and how it should be changed

**Comment by dikwickley** [comment]
@mrava87 is this issue open? if yes I'd like to work on this.

**Comment by mrava87** [comment]
Kind of but since we moved to v2 already it is sort of pointless now... I will close it.
