### ISSUE TITLE
Bug: Convolve1D when dims is scalar and method='direct'

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#358]
# Problem
The new version of Convolve1D without the parameter `N` and only `dims` is bugged when working with 1d signals (`dims` is a scalar) and choosing `method=direct`. This is because the `_choose_convfunc` internal method checks for `dims` being `None` instead of being a scalar (previous behaviour in the presence of `N`

# Solution
A simple change can be introduced in the `_choose_convfunc` to check the type of dims instead of checking for None. In case this is int (or float to be on the safe side) we need to enter the first block of if statement which selects the correct method for the 1d case. This allows the `direct` one.

**Comment by cako** [comment]
Closed by #359
