### ISSUE TITLE
Bug: FFT v1.18 inconsistent with v1.16

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#362]
# Problem
A student of mine moved from v1.14 to v1.18 and suddenly his code stopped working. We believe we have narrowed down the issue to the `FFT` operator and a small test showed we are likely to be right:

```
from FFT_18 import FFT as FFT_18
from FFT_16 import FFT as FFT_16

nx = 1002
x = np.random.normal(0, 100, nx)

FFTop16 = FFT_16(nx, real=True, dtype=np.float32)
FFTop18 = FFT_18(nx, real=True, dtype=np.float32)

err = FFTop16 @ x - FFTop18 @ x

plt.figure()
plt.plot(np.real(err))

plt.figure()
plt.plot(np.imag(err))
```

(note that I am just locally copying the FFT and _BaseFFTs (for v1.18) so I can call them together). There is a huge mismatch, and trying various parameters the one responsible for it seems to be `real=True`.

@cako I am going to dig deeper into this but if you can also take a look and maybe spot where the issue is that would be great :D

**Comment by mrava87** [comment]
@hongyx11 follow this :)

**Comment by mrava87** [comment]
Ok, this was easy!

The problem is in `y[..., 1 : 1 + (self.nfft - 1) // 2] *= np.sqrt(2)` which we added to make the real code be adjoint. @hongyx11 could it be that this extra `sqrt(2)` makes your code go overflow?

**Comment by hongyx11** [comment]
this y is output of fft and input of matvec right? yes maybe, I will  do some change to consider this. So the diff between 1.16 and 1.18 in FFT is reasonable now?

**Comment by mrava87** [comment]
Indeed, for our application this is what gets fed to the matvec :)

In v1.16 we had a version of FFT with real input that was not passing the adjoint test. This is because real FFT is not clinear but just linear. So we needed to make some changes to allow also rlinear operators in PyLops and one of them was to 'fix' the FFT. In other words, FFT in v1.16 with `real=True` was not correct, unless you have both FFT and FFT.H in the same operator (which is the case for the one you work on). If interested in the details see https://github.com/PyLops/pylops/issues/268

For us, we could try a very quick fix dividing by sqrt(2) before applying matvec and reapplying sqrt(2) after, just to see if things go back to working... if yes, then maybe we can think of a smarter way

**Comment by hongyx11** [comment]
Yes, now our code works with 1.18. Thanks!

**Comment by cako** [comment]
Ummmmm, maybe the sqrt(2) isnt the best option? I'm honestly not sure. One option is to remove the sqrt(2) from the forward and put whatever scaling needs to be put to respect the dot product only on the backward? Whatever it is, this has to be very very well documented/explicit, because since experienced users are facing this, newer users will for sure have issues.

**Comment by mrava87** [comment]
I agree. I remember we had a looong discussion with Alan on this, so I am quite sure the sqrt(2) was a well thought choice - which perhaps we have not documented very clearly in the doc. I’ll try to take a look back and that issue and see if we can make this more explicit.

Note that for us (@hongyx11 work) we are using low precision (eg int8) within a MDC operator and so we are prone to overflow if we are not careful on how to rescale things. His implementation worked wirh v16 and started to crash on v18 just because an extra sqrt(2) appeared in the FFT, but I think we can handle this - it is just a matter of being aware ;)


PS: your suggestion of putting only the scaling in the backward sounds a bit like what we already offer for nfft, I don’t know if it is wise to also offer one for the 2 factor for real or it will just make things ever more complicated?

**Comment by cako** [comment]
Can this issue be closed?

**Comment by hongyx11** [comment]
I think so
