### ISSUE TITLE
Solvers file organization

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#390]
## Motivation
In https://github.com/PyLops/pylops/pull/363 and https://github.com/PyLops/pylops/pull/384, the `optimization` module has been modified to accommodate for class-based solvers. However, the last solution has both class- and function-based solvers in the same file. This creates a nasty problem in the documentation as those solvers have same name (the only difference is capital versus lower case).

## Solution
I suggest to reintroduce what used to be an intermediate solution (that was later abandoned), with a small change. Class based solvers are moved to `cXX` files whilst function-based solvers stay in `XX`. Having `c` as prefix is much easier to remember for devs than having `c` as suffix (like it was done in the intermediate solution), and makes it easy to have a nice documentation

**Comment by cako** [comment]
Could we do `fun_` and `cls_` instead of `c` prefix?

**Comment by mrava87** [comment]
I don’t like it, especially because having nothing for the function will avoid a breaking change that I don’t see being very beneficial. We could have cls_basic etc, if you think that helps

**Comment by cako** [comment]
That sounds good!
