### ISSUE TITLE
Clean up unused input parameters in MDC, MDD and Marchenko routines

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#392]
# Problem

At various stages of development, a number of parameters in these routines were deprecated in favor of others. However to maintain backward compatibility such parameters could not be 

# Definition of done
- Remove all deprecated parameters and re-arrange the order of inputs
- Fix tests and tutorials

**Comment by cako** [comment]
Does #393 close this?

**Comment by mrava87** [comment]
Yes :)
