### ISSUE TITLE
FunctionOperator n and m arguments are not optional

### ISSUE THREAD

**Issue by crsanderford** [PyLops/pylops#417]
Running on Windows 10, pylops version 1.18.3.

Documentation states that the operator dimension arguments aren't required for a FunctionOperator. A FunctionOperator can be constructed without these arguments, but attempting to use the FunctionOperator in any way (forward, adjoint, even printing it) leads to `AttributeError: 'FunctionOperator' object has no attribute 'shape'`.

I've produced this behavior by just using the example from the documentation without the dimension argument:

```A= pylops.basicoperators.FunctionOperator( lambda x: np.array([2*x[0], 3*x[1]]) )```

**Comment by mrava87** [comment]
Thanks for reporting this. We will look into it and get back soon

**Comment by crsanderford** [comment]
Mea culpa - I got the impression that I did from the class signature only including the `f` argument beyond `*args` and `**kwargs`, and the listing of all other parameters as optional. Your language definitely would have disambiguated the issue had I read it carefully!

**Comment by mrava87** [comment]
No worries, these things happen :)

Good to hear you agree the documentation explains this correctly. However, since you could not spot it at the first time, if you have any suggestion on how to make this point clearer please let us know
