### ISSUE TITLE
Missing files since #418

### ISSUE THREAD

**Issue by cako** [PyLops/pylops#421]
I think we jumped the gun on #418. The following files appear to be missing:

https://github.com/PyLops/pylops/blob/c564169d6554a26b431368551908cc5c5d49b905/pylops/waveeqprocessing/twoway.py#L3-L4

**Comment by mrava87** [comment]
these are from Devito! No idea why they did such a bad packaging... we have 3 options:

- accept it
- get them directly into pylops (I am not so keen on this unless we see need to modify things - this could happen at some point if we want to to Kirchoff-type LSM with wave equation as you explained in the PR)
- ask Devito to improve their packaging to have `devito.examples`... but I hardly doubt we will succeed here

**Comment by mrava87** [comment]
So long story short, if you install Devito this should work. It does for me and on the CI so I am quite confident it should for you too :)

**Comment by mrava87** [comment]
But perhaps you meant I forgot to protect the import of Devito since it is an optional dependency. I did it now :)
