### ISSUE TITLE
Migrate documentation to Python3.9 and use new template

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#443]
# Motivation
The PyLops documentation has not changed in a while in terms of setup and layout. We are in need of some improvement to ensure its long-term life.

# Definition of done
- The documentation in RTD is currently built using Python3.8 -> convert to Python3.9. This requires using RTD config-v2: https://docs.readthedocs.io/en/stable/config-file/v2.html
- Change template to the `pydata-sphinx-theme`

**Comment by dikwickley** [comment]
hi @mrava87 i would like to work on this, can you assign this issue to me?

**Comment by mrava87** [comment]
Sure, that would be great! 

Assigned :)

**Comment by cako** [comment]
Is this closed by #475?

**Comment by mrava87** [comment]
Yes, thanks @dikwickley

**Comment by mrava87** [comment]
Documentation is live here: https://pylops.readthedocs.io/en/latest/ 😀

**Comment by cako** [comment]
Looks awesome!!
