### ISSUE TITLE
Pip installing from git cloned repo gives wrong version

### ISSUE THREAD

**Issue by cako** [PyLops/pylops#464]
## Steps to Reproduce

Follow dev install instructions for conda env [described in the docs](https://pylops.readthedocs.io/en/stable/installation.html#step-by-step-installation-for-developers). Then pip install the folder:
```bash
(pylopsenv) user@hostname:~/cako/pylops$ pip install -e .
Obtaining file:///home/user/pylops
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.21.0 in /home/user/miniconda3/envs/pylopsenv/lib/python3.10/site-packages (from pylops==1.18.1.dev308+g84a428e) (1.23.5)
Requirement already satisfied: scipy>=1.4.0 in /home/user/miniconda3/envs/pylopsenv/lib/python3.10/site-packages (from pylops==1.18.1.dev308+g84a428e) (1.9.3)
Installing collected packages: pylops
  Running setup.py develop for pylops
Successfully installed pylops-1.18.1.dev308+g84a428e
```

The installation should say `Successfully installed pylops-2.0.0.dev308+g84a428e` or something similar.

**Comment by mrava87** [comment]
Mmh, the only thing I can think of is that your fork is not up to date with the tags, could that be the case?

I just cloned the main repo and `pip install -e .` and I get `Successfully installed pylops-2.0.1.dev32+g60c75bc`

**Comment by cako** [comment]
I realized I was from my fork that didn't have updated tags!!
