### ISSUE TITLE
Typo in Tutorials section 3 on solvers

### ISSUE THREAD

**Issue by Dhruv88** [PyLops/pylops#503]
The following equation: 
![image](https://user-images.githubusercontent.com/55611035/229056361-4e1482c1-e08e-4b2a-9d14-4de82da02fa8.png)
Here the **R** and **y** are in superscript but that should not be the case. In version `1.18.3` this problem is not there and seems to start appearing from `v2.0.0` docs. It is also present in the latest and stable docs.

**Comment by mrava87** [comment]
Thanks a lot for spotting this. This is definitely a typo, we will fix it :)
