### ISSUE TITLE
pylops.utils.signalprocessing.convmtx Returns incorrect dimensions

### ISSUE THREAD

**Issue by austinlb001** [PyLops/pylops#517]
The function listed in the title does not operate correctly.  My "h" is a 30x1 matrix that I transposed and indexed the zeroth row so it became a 1 dimensional array.  Then my "n" is 512. Since the len(h) < n, then the dimensions of the matrix returned should be 541x512, but 512x541 was returned.  Please correct this to match MATLAB since you are claiming it is the MATLAB equivalent function, and to match scipy.linalg.convolution_matrix().

**Comment by mrava87** [comment]
Hello @austinlb001, thanks for noticing this. 

Let me take a look, I agree this seems to be a wrong behavior .

**Comment by mrava87** [comment]
Hi again, 
after close inspection, you are right that `pylops.utils.signalprocessing.convmtx` does not behave as described in the doc. 

Unfortunately I remember taking this code online and trusting the fact it was reproducing MATLAB's convmtx as at that time I did not have access to MATLAB, I should have checked!

Usually we do not like making breaking changes as part of minor releases but I flag this more as a bug fix than a breaking change and I have documented it with a warning to make sure users become aware of the proposed change. What I have now behaves basically like `scipy.linalg.convolution_matrix()` (which I do not recall being available at that time...) with `mode='same'` for `offset=0` and as a shifted version of `scipy.linalg.convolution_matrix()`'s matrix for other offsets... the idea for us is to match our `pylops.signalprocessing.Convolve1D` operator as there are scenarios where it may be better to make the explicit matrix than using the equivalent linear operator.

I am currently on holiday and can't access MATLAB. It would be great if you can check that we are now matching MATLAB before I merge the PR (see https://github.com/PyLops/pylops/pull/521)

**Comment by mrava87** [comment]
@austinlb001 just checking you saw my message above...

**Comment by austinlb001** [comment]
Hey,

Sorry for the delay.  I got the chance to check it. The dimensions are correct but the output is completely wrong.  `scipy.linalg.convolution_matrix()` has the correct output.

**Comment by mrava87** [comment]
Ok, ill take a look as I checked and at least for the case n>len(h) I am quite sure we had the same output… note that I may change the docstring and remove the matlab comment as what we need to function to do is to match our Convolve1D operator and this can be slightly different than scipy’s one unless you choose mode=‘same’…

**Comment by mrava87** [comment]
Right, I see that there are still some inconsistencies. I may not be able to look into this in the next few weeks, but I will come back and try to finalize it such that it matches MATLAB `convmtx` as much as possible and it is coherent with our Convolve1d operator

**Comment by mrava87** [comment]
Alright, I think I have now a working version which aligns with our Convolve1D operator as well as with matlab/scipy (for some specific choice of parameters) - as described in the docstring.

Here is an example with a small filter (n>nh):

```
n = 512
nh = 17
h, _, offset = ricker(np.arange(nh)*0.004, 15)
offset = offset+10
nh = len(h)
Fop = FirstDerivative(h.shape)
h = Fop @ h * 5

H = convmtx(h, n, 0)
H1 = sp.linalg.convolution_matrix(h, n, mode='full')
H2 = Convolve1D(n, h, offset=0).todense()

print(H.shape, H1.shape, H2.shape)
print(np.allclose(H, H1), np.allclose(H[:n], H2))
```

and large filter (n<nh):

```
n = 512
nh = 17
x = np.zeros(n)
x[n//2] = 1

X = convmtx(x, len(h), 0)
X1 = sp.linalg.convolution_matrix(x, nh, mode='full')
X2 = Convolve1D(len(h), x, offset=0).todense()

print(X.shape, X1.shape, X2.shape)
print(np.allclose(X, X1), np.allclose(X[:n], X2))
```

**Comment by mrava87** [comment]
@austinlb001 can you give me a feedback when you have time so I can merge the PR :)
