### ISSUE TITLE
cannot import name '_get_dtype' from 'scipy.sparse.linalg.interface'

### ISSUE THREAD

**Issue by mirmusz** [PyLops/pylops#524]
Hello Dr @mrava87 ,

I am Miru, a postgraduate student. I am learning about Marchenko redatuming. Currently, I am trying to install pylops_distributed on my machine. However, I am stuck with an import error as shown in the attached picture. I am not sure where is the root cause for this error as I tried to install-reinstall differents version of numpy,scipy etc. to make it works. Appreciated if you can help me on this matter. Thanks.

![image](https://github.com/PyLops/pylops/assets/87347555/cca65034-cb42-46d1-b990-5d3dc7155b85)

**Comment by mrava87** [comment]
Hello @mirmusz,
it would be better if you open the issue in the related library. However, I can already tell you `pylops_distributed` is unfortunately unmaintained as we realized it was not the right direction when it comes to leveraging distributed computing in Python. You may want to look into our newly created library http://github.com/pylops/pylops-mpi which we believe does this in a much better way. We haven't 

The issue you have can be simply solved, I think you are just using a too recent version of SciPy. I suspect you install this environment https://github.com/PyLops/pylops-distributed/blob/master/environment.yml? Probably by just limiting scipy to be <1.8.0 and pylops to be <2.0.0 you will solve the issue, but I wanted to give you an heads up as if I were you I would not use pylops_distributed, rather look into our new library.

Also, a more general question, if you are new to Marchenko, why do you want to start with a distributed version of it... using Pylops's Marchenko or even better http://github.com/dig-kaust/pymarchenko would get you a long way in terms of learning and maybe implementing new ideas before having to move to something more performant if you want to tackle 3d problems :)

**Comment by mrava87** [comment]
Hello, given no reply I close this issue
