### ISSUE TITLE
incorrect check on dips argument in in `slope_estimation

### ISSUE THREAD

**Issue by Beramos** [PyLops/pylops#572]
The documentation states the following: 

![image](https://github.com/PyLops/pylops/assets/11618908/1d32eee6-3914-4a3a-a638-a097b130cadc)

However, the logic flow in the code is the opposite:

https://github.com/PyLops/pylops/blob/0d19f5689978cb71e743bf673d4ce775e22817c6/pylops/utils/signalprocessing.py#L249-L253

I double checked with the original implementation of `dips_estimate` 

https://github.com/PyLops/pylops/blob/c5844c4a4b25cdb74a5cef12b926d6d91da20095/pylops/utils/signalprocessing.py#L79-L182

And it is inline with the current documentation. It appears that the bug was introduced when `dips_estimate` and slope_estimate` merged.  

I have a PR ready for this.

**Comment by mrava87** [comment]
Thanks @Beramos for noticing this.

@cako, since you did quite some changes to this part of the code, do you agree with this? If so, I can go ahead and merge the PR

**Comment by mrava87** [comment]
@cako?
