### ISSUE TITLE
Class based solvers

### ISSUE THREAD

**Issue by mrava87** [PyLops/pylops#90]
## Change

Move from function based to class based solvers. This would require creating a base class with the following:

- `__init__`
- `step`: run a single step 
- `callback`: run after any step (a user can just overwrite it - currently is passed to the solver as function)
- `print`: print update
- `solve`: run entire solver

## Motivation

- This allows running multiple inversion with different solver parametrization (niter, tol, etc) without having to rerun the preparation part, which could be time consuming and independent on the solver parameters.
- This allows users to run both the solver as is or run it in a more fine-grained fashion (using `step`). 

## Countermotivation

- This is a breaking change, is it worth?
- Scipy has function based solvers, if we move away from them (for also `cg`, `cgls`, `lsqr`) we will need to call them differently inside our apps depending on whether we use numpy or cupy arrays - right now we just call a different solver but with a very similar function signature.

**Comment by marcusvaltonen** [comment]
This is really the way to go. I just want to add code reusability as part of the motivation.
